name: Clear Path Solutions
favicon: null
layout_spectrum: 0.6163105894811451
typography_spectrum: 0.25125
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00aae2'
    - '#ffb131'
    - '#797979'
    - '#b3b3b3'
  brandStrength: 0.568200312089175
  lightness: 0.8257056677248329
  saturation: 0.25
  rhythmicContrast: 0.034667838364839554
purpose: []
